# Generated by Django 4.2.18 on 2025-02-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_alter_orderdetails_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Failed'), (3, 'Cancelled'), (4, 'Refunded'), (5, 'Chargeback'), (6, 'On Hold'), (7, 'Processing'), (8, 'Partially Paid'), (9, 'Awaiting Payment'), (10, 'Authorized')], default=0)),
                ('payment_method', models.IntegerField(choices=[(0, 'Cash'), (1, 'Gcash'), (2, 'Bank Transfer'), (3, 'Other')], default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
