# Generated by Django 4.2.18 on 2025-02-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, verbose_name='Store Name')),
                ('login_header_message', models.TextField(blank=True, null=True, verbose_name='Login Header Message')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/', verbose_name='Favicon')),
                ('timezone', models.CharField(default='UTC', max_length=100, verbose_name='Timezone')),
                ('store_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Store Latitude')),
                ('store_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Store Longitude')),
            ],
            options={
                'verbose_name': 'Store Setting',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
