# Generated by Django 4.2.18 on 2025-02-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='currency',
            field=models.CharField(default='USD', max_length=10, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='currency_symbol',
            field=models.CharField(default='$', max_length=5, verbose_name='Currency Symbol'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='firebase_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Firebase API Key'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='firebase_auth_domain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Firebase Auth Domain'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='gmap_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Maps API Key'),
        ),
    ]
