# Generated by Django 4.2.18 on 2025-02-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_storesettings_currency_storesettings_currency_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='store_latitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Store Latitude'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='store_longitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Store Longitude'),
        ),
    ]
