# Generated by Django 4.2.18 on 2025-02-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_storesettings_store_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='currency',
            field=models.CharField(default='PHP', max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='currency_symbol',
            field=models.CharField(default='₱', max_length=5, verbose_name='Currency Symbol'),
        ),
    ]
