"""
Django settings for waterrefill project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rz#k-y#odp(t@3%%0j&hj1b(h2df*c$3uc=*!kr^nl-(!4xm5('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
#ALLOWED_HOSTS = ['157.173.221.215','refillpro.store']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
    'rest_framework',
    'rest_framework_simplejwt',
    'admin_portal',
    'api',
    'products',
    'orders',
    'payments',
    'settings'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'waterrefill.urls'
STATICFILES_DIRS = [BASE_DIR / 'admin_portal/static']
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'admin_portal/templates',BASE_DIR / ''],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'waterrefill.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'waterrefill',
        'USER': 'root',
        'PASSWORD': '',
        #'PASSWORD': 'Informatics@2025',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=3),  # Access token valid for 1 hour
    'REFRESH_TOKEN_LIFETIME': timedelta(days=10),  # Refresh token valid for 7 days
    'ROTATE_REFRESH_TOKENS': True,  # Refresh token rotation enabled
    'BLACKLIST_AFTER_ROTATION': True,  # Blacklist old tokens after rotation
}

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'admin_portal.CustomUser'



JAZZMIN_SETTINGS = {
    "site_title": "My Admin",
    "site_header": "My Dashboard",
    "welcome_sign": "Welcome to RefillPro Admin Panel",

    # 🔹 Control Sidebar Order
    "order_with_respect_to": [
        "admin_portal.CustomUser",
        "product.Product",  # Keep products grouped properly
        "orders.Order",  # Keep products grouped properly
        "auth.Group",
    ],
   "hide_models": [
        "admin_portal.CustomUser",      # Hides default Django Users section
        "products.Product" ,
        "orders.Order",
        "orders.OrderDetails",
        "payments.Payment",
        "settings.StoreSettings",
        "auth.Group"    # Hides the separate "Products" section
    ],

    "navigation_expanded": True,

    # 🔹 Customize Icons
    "icons": {
        "auth.User": "fas fa-user",
        "admin_portal.CustomUser": "fas fa-users",
        "product.Product": "fas fa-box",
        "auth.Group": "fas fa-user-shield",
    },

    # 🔹 Group Users & Products Together
    "custom_links": {
        "admin_portal": [  # Keep everything under "Users"
            {
                "name": "Manage Users",
                "url": "admin:admin_portal_customuser_changelist",
                "icon": "fas fa-user",
            },
            {
                "name": "Manage User Group",
                "url": "/admin/auth/group/",
                "icon": "fas fas fa-users",
            },
            
            {
                "name": "Manage Products",
                "url": "/admin/products/product/",
                "icon": "fas fa-box-open",
            },
            {
                "name": "Orders",
                "url": "/admin/orders/order/",
                "icon": "fas fa-shopping-cart",
            },
             {
                "name": "Payments",
                "url": "/admin/payments/payment/",
                "icon": "fas fa-money-bill-wave",
            },
             {
                "name": "Settings",
                "url": "/admin/settings/storesettings/1/change/",
                "icon": "fas fa-cogs",
            },
        ],
    },
}



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.authentication.CustomJWTAuthentication',
    ),
}


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'sandbox.smtp.mailtrap.io'  # Use your email provider's SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = '9021c0f8aac191'  # Replace with your email
EMAIL_HOST_PASSWORD = '4cecdcdbd24b41'  # Use an app password for security