# Generated by Django 4.2.18 on 2025-01-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firebase_tokens',
            field=models.TextField(default=''),
        ),
    ]
