# Generated by Django 4.2.18 on 2025-01-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_customuser_firebase_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Client'), (1, 'Rider'), (2, 'Admin')], default=0),
        ),
    ]
