# Generated by Django 4.2.18 on 2025-01-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0004_themesettings_customuser_address_customuser_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
