# Generated by Django 4.2.18 on 2025-01-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0005_alter_customuser_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
