# Generated by Django 4.2.18 on 2025-01-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0006_alter_customuser_lat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=15, null=True),
        ),
    ]
