# Generated by Django 4.2.18 on 2025-01-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0007_alter_customuser_lat_alter_customuser_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='long',
            field=models.TextField(blank=True, null=True),
        ),
    ]
