# Generated by Django 4.2.18 on 2025-01-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='product_ids',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='product_ids',
            field=models.ManyToManyField(related_name='order_details', to='products.product'),
        ),
    ]
