# Generated by Django 4.2.18 on 2025-01-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderdetails_product_ids_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name': 'Order Detail', 'verbose_name_plural': 'Order Details'},
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
