# Generated by Django 4.2.18 on 2025-02-01 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0004_orderdetails_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='product_ids',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='products.product'),
        ),
    ]
