# Generated by Django 4.2.18 on 2025-02-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderdetails_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='delivery_datetime',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Delivered'), (2, 'Cancelled')], default=0),
        ),
    ]
