# Generated by Django 4.2.18 on 2025-02-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_water_product_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_alert_level',
            field=models.IntegerField(default=0),
        ),
    ]
